on:
  workflow_dispatch: ~
  push:
    branches: ['main', '*.*.x']
  pull_request: ~

jobs:
  check:
    uses: thesis-php/.github/.github/workflows/check.yml@main
    with:
      php_versions: '["8.4"]'
    secrets: inherit
